org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false

minecraft_version=26.1.2
loader_version=0.19.3
fabric_version=0.154.2+26.1.2
loom_version=1.15.5
blendlib_version=1.0.0-alpha.1+26.1.2
blendlib_sha256=7a3d06392c068d6bc58883f24e16dd1ee08cd0219e0f37ae6b3e9ac82515387b

mod_version=0.1.0-alpha.2
maven_group=com.liy.ancientdragon
archives_base_name=ancient-dragon
