org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false

minecraft_version=26.1.2
loader_version=0.19.3
fabric_version=0.154.2+26.1.2
loom_version=1.15.5
blendlib_version=1.0.0-beta.2+26.1.2
blendlib_release_tag=v1.0.0-beta.2
blendlib_sha256=01a1cabe230da43222fe30baab23d3f31ed7f09868601c7d81cac9b82f5d83de

mod_version=0.1.0-beta.1+26.1.2
maven_group=com.liy.ancientdragon
archives_base_name=ancient-dragon
