package com.liy.ancientdragon.worldgen;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import java.util.Optional;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.datafix.DataFixTypes;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.saveddata.SavedDataType;

/** Restart-safe progress for repairing mountains generated by the legacy one-start layout. */
public final class SacredMountainNaturalRepairData extends SavedData {
    public static final Codec<SacredMountainNaturalRepairData> CODEC = RecordCodecBuilder.create(instance ->
            instance.group(Job.CODEC.optionalFieldOf("job").forGetter(data -> data.job))
                    .apply(instance, SacredMountainNaturalRepairData::new));

    public static final SavedDataType<SacredMountainNaturalRepairData> TYPE = new SavedDataType<>(
            Identifier.fromNamespaceAndPath("ancient_dragon", "sacred_mountain_natural_repair"),
            SacredMountainNaturalRepairData::new,
            CODEC,
            DataFixTypes.SAVED_DATA_COMMAND_STORAGE);

    private Optional<Job> job;

    public SacredMountainNaturalRepairData() {
        this(Optional.empty());
    }

    private SacredMountainNaturalRepairData(Optional<Job> job) {
        this.job = job == null ? Optional.empty() : job;
    }

    public static SacredMountainNaturalRepairData get(ServerLevel level) {
        return level.getServer().overworld().getDataStorage().computeIfAbsent(TYPE);
    }

    public Optional<Job> job() {
        return job;
    }

    public void begin(String structureSha256, BlockPos anchor, int quarterTurns, int repairVersion) {
        job = Optional.of(new Job(
                structureSha256,
                anchor.immutable(),
                Math.floorMod(quarterTurns, 4),
                repairVersion,
                0,
                0,
                0L,
                Status.RUNNING,
                ""));
        setDirty();
    }

    public void advance(int nextTileIndex, int repairedTiles, long changedBlocks) {
        Job current = requireJob();
        job = Optional.of(current.withProgress(nextTileIndex, repairedTiles, changedBlocks));
        setDirty();
    }

    public void complete() {
        Job current = requireJob();
        job = Optional.of(current.withStatus(Status.COMPLETE, ""));
        setDirty();
    }

    public void fail(String issue) {
        Job current = requireJob();
        job = Optional.of(current.withStatus(Status.FAILED, issue));
        setDirty();
    }

    private Job requireJob() {
        return job.orElseThrow(() -> new IllegalStateException("Missing natural Sacred Mountain repair job"));
    }

    public enum Status {
        RUNNING("running"),
        COMPLETE("complete"),
        FAILED("failed");

        public static final Codec<Status> CODEC = Codec.STRING.xmap(Status::parse, Status::serializedName);
        private final String serializedName;

        Status(String serializedName) {
            this.serializedName = serializedName;
        }

        public String serializedName() {
            return serializedName;
        }

        private static Status parse(String value) {
            for (Status status : values()) {
                if (status.serializedName.equals(value)) {
                    return status;
                }
            }
            return FAILED;
        }
    }

    public record Job(
            String structureSha256,
            BlockPos anchor,
            int quarterTurns,
            int repairVersion,
            int nextTileIndex,
            int repairedTiles,
            long changedBlocks,
            Status status,
            String issue) {
        public static final Codec<Job> CODEC = RecordCodecBuilder.create(instance -> instance.group(
                Codec.STRING.fieldOf("structure_sha256").forGetter(Job::structureSha256),
                BlockPos.CODEC.fieldOf("anchor").forGetter(Job::anchor),
                Codec.INT.optionalFieldOf("quarter_turns", 0).forGetter(Job::quarterTurns),
                Codec.INT.optionalFieldOf("repair_version", 1).forGetter(Job::repairVersion),
                Codec.INT.optionalFieldOf("next_tile_index", 0).forGetter(Job::nextTileIndex),
                Codec.INT.optionalFieldOf("repaired_tiles", 0).forGetter(Job::repairedTiles),
                Codec.LONG.optionalFieldOf("changed_blocks", 0L).forGetter(Job::changedBlocks),
                Status.CODEC.fieldOf("status").forGetter(Job::status),
                Codec.STRING.optionalFieldOf("issue", "").forGetter(Job::issue)
        ).apply(instance, Job::new));

        public Job {
            if (structureSha256 == null || !structureSha256.matches("[0-9a-f]{64}")
                    || anchor == null || repairVersion <= 0 || nextTileIndex < 0
                    || repairedTiles < 0 || changedBlocks < 0L
                    || status == null || issue == null) {
                throw new IllegalArgumentException("Incomplete natural Sacred Mountain repair job");
            }
            quarterTurns = Math.floorMod(quarterTurns, 4);
        }

        Job withProgress(int newNextTileIndex, int newRepairedTiles, long newChangedBlocks) {
            return new Job(structureSha256, anchor, quarterTurns, repairVersion,
                    newNextTileIndex, newRepairedTiles,
                    newChangedBlocks, status, issue);
        }

        Job withStatus(Status newStatus, String newIssue) {
            return new Job(structureSha256, anchor, quarterTurns, repairVersion,
                    nextTileIndex, repairedTiles,
                    changedBlocks, newStatus, newIssue);
        }
    }
}
